### ISSUE TITLE
auth_param syntaxe error

### ISSUE THREAD

**Issue by clems94** [voxpupuli/puppet-squid#10]
Hello i use this configuration on my profile puppet

# Squid proxy
class profiles::squid_proxy {

class{'::squid':}
squid::http_port{'8080':
options => '',
}

squid::auth_param{ 'basic auth_param':
  scheme    => 'basic',
  entries   => ['program /usr/lib64/squid/basic_ncsa_auth /etc/squid/passwords',
                'children 5',
                'realm Squid Basic Authentication',
                'credentialsttl 1 hours'],
  order     => '5',
}

squid::acl{'snsi':
  type    => src,
  entries => ['10.10.10.0/24'],
}

squid::acl{'user':
  type    => proxy_auth,
  entries => ['REQUIRED'],
}

squid::http_access{'snsi user':
  action => allow,
}

squid::cache_dir{'/var/squid/':
  type           => 'ufs',
  options        => '15000 32 256 min-size=32769',
}

}

When i apply this configuration i've got an error to launch squid, becaus the lines 
auth_param basic children 5
auth_param basic credentialsttl 1 hours
auth_param basic program /usr/lib64/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm Squid Basic Authentication 

are under the line 
# acl fragment for user
acl user proxy_auth REQUIRED

Is someone met this error ?

**Comment by traylenator** [comment]
You added an explicit
```puppet
order => '5',
```

in there which will push the auth lines very early.

Is it true the acl user lines should always happen early in the file?

**Comment by traylenator** [comment]
As far I know  I have answered this.

**Comment by alexjfisher** [comment]
@traylenator I'm not sure the `order => '5'` is the problem?

The current code in auth_param.pp has
```puppet
concat::fragment{"squid_auth_param_${auth_param_name}":
  # SNIP #
  order   => "40-${order}-${scheme}"
```
so specifying an explicit `order` only orders the `auth_params` with respect to each other?  They still all appear after the `acl`s

**Comment by traylenator** [comment]
@alexjfisher I'll have a proper look at this on Monday.

**Comment by alexjfisher** [comment]
Fixed in https://github.com/voxpupuli/puppet-squid/issues/21
