### ISSUE TITLE
Incompatible with released version of puppetlabs-stdlib

### ISSUE THREAD

**Issue by tpdownes** [voxpupuli/puppet-squid#130]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent-5.5.14-1.el7.x86_64
- Ruby: ?
- Distribution: CentOS
- Module version: 2.2.0

## How to reproduce (e.g Puppet code you use)
```
sudo -i puppet module install puppet-squid --version 2.2.0
```
## What are you seeing
Failed installation of `puppet-squid` claiming dependency resolution cannot succeed.

## What behaviour did you expect instead
`puppet-squid` installation should succeed.

## Output log
```
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'puppet-squid' (???)
  No version of 'puppet-squid' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

## Any additional information you'd like to impart
`puppetlabs-stdlib` 6.0.0 was just released today so not surprising and will require testing. It does not appear to be a problem with the direct dependency claim in the `puppet-squid` metadata. It can be resolved by downgrading `puppetlabs-stdlib` to 5.2.0 and re-trying installation.

The [release notes](https://forge.puppet.com/puppetlabs/stdlib/changelog) don't look scary but there are a [number of commits behind the major version change](https://github.com/puppetlabs/puppetlabs-stdlib/compare/5.2.0...v6.0.0).

**Comment by mmoll** [comment]
GH-131 might fix this.

**Comment by bastelfreak** [comment]
Hi. I'm doing a new release in https://github.com/voxpupuli/puppet-squid/pull/132 which fixes this.
