### ISSUE TITLE
no option for squid configuration directive 'hosts_file'

### ISSUE THREAD

**Issue by taleintervenor** [voxpupuli/puppet-squid#165]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: unrelated
- Ruby: unrelated
- Distribution: unrelated
- Module version: 3.0.0

## Problem

according to squid official doc: http://www.squid-cache.org/Doc/config/hosts_file/ , directive '**hosts_file**' need to be set in order to use the local hosts file. But this puppet module didn't provide option to set this directive.

**Comment by traylenator** [comment]
Not against adding an option but the docs to me suggest that
```
hosts_file /etc/hosts
```

is the default anyway, so unless you want to use an alternate location I don't think it is needed ?
