### ISSUE TITLE
Request release of v3.0.1

### ISSUE THREAD

**Issue by kim-sondrup** [voxpupuli/puppet-squid#168]
Having dependency problems with [puppetlabs-stdlib 8.1.0](https://forge.puppet.com/modules/puppetlabs/stdlib/8.1.0) since puppet-squid v3.0.0 are set to depend on version range [">= 4.25.0 < 7.0.0"](https://github.com/voxpupuli/puppet-squid/blob/v3.0.0/metadata.json#L32-L33)

Request to have version 3.0.1 released since the main branch already contains [the fix](https://github.com/voxpupuli/puppet-squid/blob/cb689255f723ff20377b7ebca3d00f43f5e11c86/metadata.json#L32-L33).

**Comment by kobybr** [comment]
+1

**Comment by fayelund** [comment]
+1

**Comment by kim-sondrup** [comment]
Closing issue since [v4.0.0](https://forge.puppet.com/modules/puppet/squid/4.0.0) have been released
