### ISSUE TITLE
Puppet 7 support

### ISSUE THREAD

**Issue by bk-lg** [voxpupuli/puppet-squid#172]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby:-
- Distribution:-
- Module version:-

## What are you seeing
There is no support for puppet 7.
## What behaviour did you expect instead
Puppet 7 as supported version.
## Any additional information you'd like to impart
Hey,

has anyone already plans to update this module to support puppet7?

**Comment by smortex** [comment]
It looks like #164 added support for Puppet 7 but no release was issued since. Do you want to give it a try?

Anyone can submit a RP to release a new version, the process is documented here:
https://voxpupuli.org/docs/releasing_version/ (you can ignore the first step related to modulesync)

**Comment by bk-lg** [comment]
@smortex I created the pull request and hope that everything is correct.
