### ISSUE TITLE
Minor enhancement request

### ISSUE THREAD

**Issue by dshepherd-descartes** [voxpupuli/puppet-squid#31]
extra_config_section only takes a hash of parameters.  That means you cannot configure repeating keys within the same extra_config_section, even if that would make sense.

It would be nice if it could read a list as well as a hash.  This could be a list of hashes for convenience of parsing.

**Comment by dshepherd-descartes** [comment]
Here is a patch against 0.3.0 that performs the changes necessary to support importing a list of hashes (and retains the old behaviour for hashes as well).  I hope it works for you.

[puppet-squid-extra-config.diff.txt](https://github.com/voxpupuli/puppet-squid/files/589548/puppet-squid-extra-config.diff.txt)

**Comment by traylenator** [comment]
@dshepherd-descartes thanks for the patch, any chance you could submit as a MR?

**Comment by jadestorm** [comment]
I'd be happy to turn this into a PR on your behalf @dshepherd-descartes if you don't really want to deal with it  -- that said you'd lose proper credit for it in github if I did that.  =/

**Comment by ralfbosz** [comment]
could somebody implement this? this would help adding things like refresh_patterns, always_direct & never_direct.

**Comment by jadestorm** [comment]
I'll go ahead and make a pull request based off the patch and we'll go from there.

**Comment by jadestorm** [comment]
https://github.com/voxpupuli/puppet-squid/pull/44

**Comment by ralfbosz** [comment]
I've been thinking about this today, but isn't it easier to just 'change' the squid.conf.extra_config_section.erb:

# <%= @comment %>
<% @config_entries.each do |k,v| -%>
<% if v.is_a?(Array) -%>
<% v.each do |v2| %>
<%= k %> <%= v2 -%>
<% end -%>
<% else -%>
<%= k %> <%= v -%>
<% end -%>
<% end -%>

I don't see the point of why the array in the extra_config_section should be put on one line with a space between. I'm busy making a push-request for this, but haven't had time yet to push it.

**Comment by jadestorm** [comment]
Probably  =)  I spent a grand total of 1 minute on this (literally just applied the patch) so if you have a better way to take care of it be my guest!  Would you like me to retract me PR or is your PR a PR to .. my .. PR.. fork.. whatever.  =)

**Comment by ralfbosz** [comment]
Since your PR is failing, the chance of it getting merges is unlikely.
I will post my PR tomorrow, hopefully with a working test, the PR is based on the "master", not on any new PR's...

**Comment by jadestorm** [comment]
Ok since you seem more enthused about pursuing this than I, I'll retract mine.  =)

**Comment by ralfbosz** [comment]
I've used the diff from @dshepherd-descartes for the manifest/extra_config_section.pp, the template-file was adjusted. Added an example in the readme and adjusted the rspec.

https://github.com/voxpupuli/puppet-squid/pull/45 is here !

**Comment by cedef** [comment]
Any news when #45 will be merged into master ? Is there anything blocking the merge ?

**Comment by ralfbosz** [comment]
It's merged !!!

**Comment by jadestorm** [comment]
@ralfbosz Awesome news!  Just wrapped back around to checking on some of the outstanding things I had going.  =)  Thanks for taking care of this!

**Comment by ekohl** [comment]
Given it's merged I'm going to close this.
