### ISSUE TITLE
puppet/selinux missing as requirement

### ISSUE THREAD

**Issue by ja391045** [voxpupuli/puppet-squid#95]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  PE 2018.1
- Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
- Distribution:  CentOS
- Module version: 1.0.0

When doing something along the lines of:
```
squid::http_port { '3129':
   ssl => true, 
   options => 'cert=whatever.pem key=whatever.pem'
}
```
The catalog cannot compile due to missing selinux::port defined type.

Log:
> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'selinux::port' at /etc/puppetlabs/code/environments/sbja/modules/squid/manifests/http_port.pp:22:5 at /etc/puppetlabs/code/environments/sbja/modules/squid/manifests/config.pp:67 on node

Recommend adding puppet/selinux to metadata.json requirements.

**Comment by ralfbosz** [comment]
What is the output of:

facter selinux

puppet/selinux is only supported on RedHat-family, so a require will not work for another OS-family.
